### ISSUE TITLE
I found a bug in eval code(need confirm)

### ISSUE THREAD

**Issue by anaivebird** [Nealcly/KE-Blender#5]
https://github.com/Nealcly/KE-Blender/blob/b0bf98f267eacaec9300aef379ceb223ab7e3d2d/eval/eval.py#L63

Correct way should be:
` res = f_one(decode_result, gold) ` since reference is the second param https://github.com/Nealcly/KE-Blender/blob/b0bf98f267eacaec9300aef379ceb223ab7e3d2d/eval/metrics.py#L84

Same problem exists in https://github.com/Nealcly/KE-Blender/blob/b0bf98f267eacaec9300aef379ceb223ab7e3d2d/eval/eval.py#L59

**Comment by Nealcly** [comment]
Thanks for your message. It is a bug for BLEU. But F1 is symmetric in the text generation setting. F1(a,b)=F1(b,a). Becasue tn=0 -> f1 = 2tp/(tp+totoal_num).

https://github.com/Nealcly/KE-Blender/blob/b0bf98f267eacaec9300aef379ceb223ab7e3d2d/eval/metrics.py#L67
